### ISSUE TITLE
Linear to Log2 Transform Correctness

### ISSUE THREAD

**Issue by deggua** [ampas/aces-core#156]
https://github.com/ampas/aces-core/blob/518c27f577e99cdecfddf2ebcfaa53444b1f9343/transforms/ctl/utilities/ACESutil.Lin_to_Log2_param.ctl#L19
~~This line doesn't make sense to me, this would result in pure black having the same Log2 encoding as middle grey~~

~~I think it makes more sense to handle the singularity and set `lg2 = -infinity`, which with proper clamping will result in 0 after normalization~~
```
float lg2 = (lin <= 0.0) ? -INFINITY : log2(lin / middleGrey);
```
Nevermind, the original works because it returns the normalized value, I see that now

https://github.com/ampas/aces-core/blob/518c27f577e99cdecfddf2ebcfaa53444b1f9343/transforms/ctl/utilities/ACESutil.Lin_to_Log2_param.ctl#L24
This line seems incomplete, it ensures the `logNorm` is >= 0, but there isn't a corresponding condition to ensure `logNorm` is <= 1

```
if (logNorm > 1.0) logNorm = 1.0;
```
i.e. clamp `logNorm` to [0, 1] so that `lin` values > `middleGrey * pow(2, maxExposure)` map to 1

I may just be confused, I'm not a professional, but I've been working with shader code related to color transforms and tonemapping.

**Comment by scottdyer** [comment]
There is no need to clamp values 1 because it is a floating point encoding. The maxExposure does not necessarily mean that there can't be values above that, it just determines what floating point value gets mapped to 1.0 in the log space. These variables allow for allocating the range and precision of the log2 shaper and how it relates to the linear encoding.
